name: actions
run-name: ${{ github.actor }} is trying to do use workflows
on: [push]
jobs:
  some_jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        run:  docker build -t actions-image .
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ../Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

