name: actions
run-name: ${{ github.actor }} is trying to do use workflows
on: [push]
jobs:
  some_jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        run:  docker build -t actions-image .
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

